/*
NOTES:
index is just so we can sort products by recommended
*/
module.exports = [
    { ///MEN / SHIRTS ///
        id: "shaped-long-tee",
        name: "Shaped Long Tee",
        type: "shirts",
        gender: "m",
        brand_id: "urban-classics",
        brand_name: "Urban Classics",
        colour: "black",
        price: 21.99,
        discount_price: 12.99,
        stock: 10,
        review_score: 2.5,
        review_count: 9,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 101
    },
    {
        id: "hale-top",
        name: "Hale Top",
        type: "shirts",
        gender: "m",
        brand_id: "vixxsin",
        brand_name: "Vixxsin",
        colour: "black",
        price: 46.99,
        discount_price: 40.99,
        stock: 5,
        review_score: 0,
        review_count: 0,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 102
    },
    {
        id: "kokomo",
        name: "Kikomo",
        type: "shirts",
        gender: "m",
        brand_id: "goodyear",
        brand_name: "GoodYear",
        colour: "grey",
        price: 32.99,
        discount_price: null,
        stock: 6,
        review_score: 0,
        review_count: 0,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 103
    },
    {
        id: "open-edge-sleeveless-tee",
        name: "Open Edge Sleeveless Tee",
        type: "shirts",
        gender: "m",
        brand_id: "urban-classics",
        brand_name: "Urban Classics",
        colour: "black",
        price: 9.99,
        discount_price: null,
        stock: 22,
        review_score: 5,
        review_count: 2,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 104
    },
    {
        id: "dead-skull",
        name: "Dead Skull",
        type: "shirts",
        gender: "m",
        brand_id: "lucky-13",
        brand_name: "Lucky 13",
        colour: "black",
        price: 39.99,
        discount_price: null,
        stock: 1,
        review_score: 3.5,
        review_count: 1,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 105
    },
    {   ///WOMEN / SHIRTS
        id: "zella-top",
        name: "Zella Top",
        type: "shirts",
        gender: "f",
        brand_id: "poizen-industries",
        brand_name: "Poizen Industries",
        colour: "black",
        price: 46.99,
        discount_price: 32.99,
        stock: 1,
        review_score: 4.5,
        review_count: 2,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 106
    },
    {
        id: "bat-top",
        name: "Bat Top",
        type: "shirts",
        gender: "f",
        brand_id: "hell-bunny",
        brand_name: "Hell Bunny",
        colour: "black",
        price: 41.99,
        discount_price: null,
        stock: 1,
        review_score: 0,
        review_count: 0,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 107
    },
    {
        id: "rock-of-ages-v-neck-t-shirt",
        name: "Rock Of Ages V-Neck T-Shirt",
        type: "shirts",
        gender: "f",
        brand_id: "liquor-brand",
        brand_name: "Liquor Brand",
        colour: "grey",
        price: 35.00,
        discount_price: null,
        stock: 12,
        review_score: 3,
        review_count: 3,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 108
    },
    {
        id: "micro-cherries-red-tank-top",
        name: "Micro Cherries Red Tank Top",
        type: "shirts",
        gender: "f",
        brand_id: "liquor-brand",
        brand_name: "Liquor Brand",
        colour: "red",
        price: 40.00,
        discount_price: null,
        stock: 12,
        review_score: 0,
        review_count: 0,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 109
    },
    {
        id: "ladies-yarn-dyed-baby-stripe-tee",
        name: "Ladies Yarn Dyed Baby Stripe Tee",
        type: "shirts",
        gender: "f",
        brand_id: "urban-classics",
        brand_name: "Urban Classics",
        colour: "green",
        price: 13.99,
        discount_price: null,
        stock: 6,
        review_score: 3.5,
        review_count: 2,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 110
    },
    {   ///MEN / SHORTS
        id: "vintage-shorts",
        name: "Vintage Shorts",
        type: "shorts",
        gender: "m",
        brand_id: "brandit",
        brand_name: "Brandit",
        colour: "black",
        price: 32.99,
        discount_price: null,
        stock: 6,
        review_score: 4.5,
        review_count: 4,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 201
    },
    {
        id: "industry-vintage",
        name: "Industry Vintage",
        type: "shorts",
        gender: "m",
        brand_id: "brandit",
        brand_name: "Brandit",
        colour: "grey",
        price: 32.99,
        discount_price: 13.99,
        stock: 6,
        review_score: 2,
        review_count: 1,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 202
    },
    {
        id: "night-camo",
        name: "Night Camo",
        type: "shorts",
        gender: "m",
        brand_id: "doomsday",
        brand_name: "Doomsday",
        colour: "green",
        price: 32.99,
        discount_price: 13.99,
        stock: 4,
        review_score: 4,
        review_count: 8,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 203
    },
    {   ///WOMEN / SHORTS
        id: "matilde",
        name: "Matilde",
        type: "shorts",
        gender: "f",
        brand_id: "khujo",
        brand_name: "Khujo",
        colour: "black",
        price: 55.99,
        discount_price: 22.99,
        stock: 15,
        review_score: 2.5,
        review_count: 6,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 204
    },
    {
        id: "ladies-highwaist-denim-lace-up-short",
        name: "Ladies Highwaist Denim Lace Up Short",
        type: "shorts",
        gender: "f",
        brand_id: "urban-classics",
        brand_name: "Urban Classics",
        colour: "black",
        price: 36.99,
        discount_price: 13.99,
        stock: 10,
        review_score: 4,
        review_count: 5,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 205
    },
    {
        id: "striped-shorts",
        name: "Striped Shorts",
        type: "shorts",
        gender: "f",
        brand_id: "fashion-victim",
        brand_name: "Fashion Victim",
        colour: "black",
        price: 55.99,
        discount_price: 26.99,
        stock: 12,
        review_score: 0,
        review_count: 0,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 206
    },
    {   ///MEN / TROUSER
        id: "graves-pant-slim-fit",
        name: "Graves Pant Slim Fit",
        type: "trousers",
        gender: "m",
        brand_id: "vixxsin",
        brand_name: "Vixxsin",
        colour: "black",
        price: 41.99,
        discount_price: 36.99,
        stock: 1,
        review_score: 5,
        review_count: 1,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 301
    },
    {
        id: "stan",
        name: "Stan",
        type: "trousers",
        gender: "m",
        brand_id: "forplay",
        brand_name: "Forplay",
        colour: "blue",
        price: 36.99,
        discount_price: null,
        stock: 13,
        review_score: 5,
        review_count: 5,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 302
    },
    {
        id: "adrian-pant-boot-cut",
        name: "Adrian Pant Boot Cut",
        type: "trousers",
        gender: "m",
        brand_id: "vixxsin",
        brand_name: "Vixxsin",
        colour: "black",
        price: 55.99,
        discount_price: 49.99,
        stock: 13,
        review_score: 5,
        review_count: 3,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 303
    },
    {   ///WOMEN / TROUSERS
        id: "akayla-trousers",
        name: "Akayla Trousers",
        type: "trousers",
        gender: "f",
        brand_id: "innocent",
        brand_name: "Innocent",
        colour: "purple",
        price: 27.99,
        discount_price: null,
        stock: 22,
        review_score: 4,
        review_count: 3,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 304
    },
    {
        id: "ladies-sarong-pants",
        name: "Ladies Sarong Pants",
        type: "trousers",
        gender: "f",
        brand_id: "urban-classics",
        brand_name: "Urban Classics",
        colour: "black",
        price: 18.99,
        discount_price: null,
        stock: 12,
        review_score: 3,
        review_count: 1,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 305
    },
    {
        id: "m65-ladies-trousers",
        name: "M65 Ladies Trousers",
        type: "trousers",
        gender: "f",
        brand_id: "brandit",
        brand_name: "Brandit",
        colour: "black",
        price: 36.99,
        discount_price: null,
        stock: 12,
        review_score: 5,
        review_count: 13,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 306
    },
    {   ///WOMEN / DRESSES///
        id: "liquor-brand-black-dress",
        name: "Liquor Brand Black Dress",
        type: "dresses",
        gender: "f",
        brand_id: "liquor-brand",
        brand_name: "Liquor Brand",
        colour: "black",
        price: 75.00,
        discount_price: null,
        stock: 10,
        review_score: 0,
        review_count: 0,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 401
    },
    {
        id: "banned-creepy-spider-zip-dress",
        name: "Banned Creepy Spider Zip Dress",
        type: "dresses",
        gender: "f",
        brand_id: "banned-apparel",
        brand_name: "Banned Apparel",
        colour: "black",
        price: 90.00,
        discount_price: null,
        stock: 10,
        review_score: 5,
        review_count: 2,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 402
    },
    {
        id: "liquor-brand-daisy-cherry-green-dress",
        name: "Liquor Brand Daisy Cherry Green Dress",
        type: "dresses",
        gender: "f",
        brand_id: "liquor-brand",
        brand_name: "Liquor Brand",
        colour: "blue",
        price: 75.00,
        discount_price: null,
        stock: 10,
        review_score: 0,
        review_count: 0,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 403
    },
    {
        id: "glasgow-dress",
        name: "Glasgrow Dress",
        type: "dresses",
        gender: "f",
        brand_id: "innocent",
        brand_name: "Innocent",
        colour: "red",
        price: 40.99,
        discount_price: 43.99,
        stock: 0,
        review_score: 5,
        review_count: 1,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 404
    },
    {
        id: "double-rainbow-dress",
        name: "Double Rainbow Dress",
        type: "dresses",
        gender: "f",
        brand_id: "jawbreaker",
        brand_name: "JawBreaker",
        colour: "black",
        price: 44.99,
        discount_price: 32.99,
        stock: 5,
        review_score: 4.5,
        review_count: 5,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 405
    },
    {   ///MEN / FOOTWEAR
        id: "phantom-tactical",
        name: "Phantom Tactical",
        type: "footwear",
        gender: "m",
        brand_id: "brandit",
        brand_name: "Brandit",
        colour: "black",
        price: 41.99,
        discount_price: 33.99,
        stock: 5,
        review_score: 5,
        review_count: 8,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 501
    },
    {
        id: "353-vegan",
        name: "353 Vegan",
        type: "footwear",
        gender: "m",
        brand_id: "altercore",
        brand_name: "Altercore",
        colour: "black",
        price: 92.99,
        discount_price: null,
        stock: 5,
        review_score: 5,
        review_count: 4,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 502
    },
    {
        id: "biker-boot",
        name: "Biker Boot",
        type: "footwear",
        gender: "m",
        brand_id: "dockers-by-gerli",
        brand_name: "Dockers by Gerli",
        colour: "black",
        price: 120.99,
        discount_price: null,
        stock: 8,
        review_score: 0,
        review_count: 0,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 503
    },
    {   ///WOMEN / FOOTWEAR
        id: "urban-decay-super-platform",
        name: "Urban Decay Super Platform",
        type: "footwear",
        gender: "f",
        brand_id: "iron-fist",
        brand_name: "Iron Fist",
        colour: "black",
        price: 75.00,
        discount_price: null,
        stock: 8,
        review_score: 0,
        review_count: 0,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 504
    },
    {   
        id: "randa-vegan",
        name: "Randa Vegan",
        type: "footwear",
        gender: "f",
        brand_id: "altercore",
        brand_name: "Altercore",
        colour: "black",
        price: 104.99,
        discount_price: 72.99,
        stock: 5,
        review_score: 0,
        review_count: 0,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 505
    },
    {   
        id: "old-skool-primary-check",
        name: "Old Skool Primary Check",
        type: "footwear",
        gender: "f",
        brand_id: "vans",
        brand_name: "Vans",
        colour: "white",
        price: 73.99,
        discount_price: null,
        stock: 3,
        review_score: 4.2,
        review_count: 7,
        hidden_by_colour: false,
        hidden_by_price: false,
        index: 506
    }
];