export const BRANDS_SUBCAT_ACTION_REQUESTED = 'BRANDS_SUBCAT_ACTION_REQUESTED';
export const BRANDS_SUBCAT_ACTION_SUCCESS = 'BRANDS_SUBCAT_ACTION_SUCCESS';
export const BRANDS_SUBCAT_ACTION_FAIL = 'BRANDS_SUBCAT_ACTION_FAIL';