export const CLOTHS_SUBCAT_ACTION_REQUESTED = 'CLOTHS_SUBCAT_FETCH_REQUESTED';
export const CLOTHS_SUBCAT_ACTION_SUCCESS = 'CLOTHS_SUBCAT_FETCH_SUCCESS';
export const CLOTHS_SUBCAT_ACTION_FAIL = 'CLOTHS_SUBCAT_FETCH_FAIL';