export const MEN_CLOTHS_SUBCAT_ACTION_REQUESTED = 'MEN_CLOTHS_SUBCAT_ACTION_REQUESTED';
export const MEN_CLOTHS_SUBCAT_ACTION_SUCCESS = 'MEN_CLOTHS_SUBCAT_ACTION_SUCCESS';
export const MEN_CLOTHS_SUBCAT_ACTION_FAIL = 'MEN_CLOTHS_SUBCAT_ACTION_FAIL';