export const WOMEN_CLOTHS_ACTION_REQUESTED = 'WOMEN_CLOTHS_ACTION_REQUESTED';
export const WOMEN_CLOTHS_ACTION_SUCCESS = 'WOMEN_CLOTHS_ACTION_SUCCESS';
export const WOMEN_CLOTHS_ACTION_FAIL = 'WOMEN_CLOTHS_ACTION_FAIL';